### ISSUE TITLE
RuntimeError: Input cannot be parsed

### ISSUE THREAD

**Issue by fabricebrito** [giannisdoukas/CWLJNIKernel#28]
Hello @giannisdoukas 

Thanks for the effort, the concept of a CWL kernel as a potential solution for https://github.com/common-workflow-language/cwltool/issues/221 is quite nice.

I've installed the kernel and did:

```
% system 
rm -f hello.tar goodbye.txt
touch goodbye.txt
tar -cvf hello.tar goodbye.txt
```

```
#!/usr/bin/env cwltool

cwlVersion: v1.0
class: CommandLineTool
baseCommand: [tar, --extract]
id: tar
inputs:
  tarfile:
    type: File
    inputBinding:
      prefix: --file
  extractfile:
    type: string
    inputBinding:
      position: 1
outputs:
  extracted_file:
    type: File
    outputBinding:
      glob: $(inputs.extractfile)
```

```
% execute tar
tarfile:
  class: File
  location: hello.tar
extractfile: goodbye.txt
```
I get "RuntimeError: Input cannot be parsed"

Do you know what's missing to get the kernel working?
